CATEGORY_CONVERSION_VALUES = {
    "companhia de saneamento": "água",
    "droga": "farmácia dia a dia",
    "parking": "carro gastos gerais",
    "sarah oliveira martins": "psicólogo fê",
    "fernanda garcia vilela": "transferencias bancárias",
    "caixa de assistencia dos funcionarios": "plano de saúde",
    "banco pan": "financiamento carro",
    "suelen pacheco tavares": "dr suelen psiquiatra",
    "eloiza barboza": "aluguel",
}

BUDGET_CATEGORY_MAPPING = {
    "contas e cartões": [
        "água",
        "aluguel",
        "assinaturas",
        "depósito",
        "financiamento carro",
        "internet",
        "luz",
        "plano de saúde",
        "psicólogo fê",
        "seguro pessoal",
        "seguro residencial",
    ],
    "Despesa não Categorizada": ["Não Categorizado"],
    "despesas dia a dia": [
        "caju code",
        "carro gastos gerais",
        "compra de imóveis etc",
        "cuidados pessoais",
        "dates",
        "dr marcus endocrinologista",
        "dr suelen psiquiatra",
        "empréstimo amigos/família",
        "estudos",
        "farmácia bimestral - uso contínuo",
        "farmácia dia a dia",
        "farmácia mensal (wegovy)",
        "faxina",
        "gatos dia a dia",
        "ifood",
        "impostos",
        "investimento",
        "jogos",
        "manutenção casa",
        "marmitas",
        "mercado",
        "nutricionista",
        "presentes",
        "ração e areia - gatos",
        "rolês amigos",
        "rolês família",
        "roupas",
        "transferencias bancárias",
        "uber",
        "viagens",
    ],
    "Receita não Categorizada": ["Não Categorizado"],
    "receitas": [
        "devolução empréstimo",
        "kake",
        "neon",
        "proventos de aplicações",
        "resgate de aplicação",
        "transferencias bancárias",
    ],
}
